import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });
import { fontHeading, fontSans, fontUrban } from "@/assets/fonts";
import { TailwindIndicator } from "@/components/ui/tailwind-indicator";
import { ModalProvider } from "@/components/providers/modal-provider";
import { Toaster } from "sonner";
import { AuthProvider } from "@/components/providers/auth-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { marketingConfig } from "@/config/marketing";
import { NavBar } from "@/components/shared/nav-bar";
import { Footer } from "@/components/shared/footer";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable,
            fontUrban.variable,
            fontHeading.variable
          )}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex min-h-screen flex-col">
              <Suspense fallback="...">
                <NavBar items={marketingConfig.mainNav} scroll={true} />
              </Suspense>
              <main className="flex-1">{children}</main>
              <Footer />
            </div>
          </ThemeProvider>
          <Toaster />
          <ModalProvider />
          <TailwindIndicator />
        </body>
      </html>
    </AuthProvider>
  );
}
